# Generated by Django 5.2.7 on 2025-11-15 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_user_balance'),
        ('wallet', '0002_remove_wallet_id_alter_wallet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user1', models.OneToOneField(db_column='account_number', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet_balance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_wallet', to='wallet.wallet')),
            ],
        ),
    ]
