# Generated by Django 5.2.7 on 2025-11-15 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user1',
            new_name='user',
        ),
    ]
