# Generated by Django 5.2.7 on 2025-11-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_user1_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='wallet_balance',
        ),
    ]
