# Generated by Django 5.2.7 on 2025-11-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paneladmin',
            name='user',
        ),
    ]
